1-module
js-tasks-ru/jsbasic-20240422_ma1rosssss pull request #2
Opened 2024-04-30 18:28 UTC by VLadislavVorobevv

2024-04-30 18:29 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-05-01 13:53 UTC, jsru-1 commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-05-01 13:58 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-05-01 14:46 UTC, koalex requested changes
Нужно решить **2-1**

2024-05-01 14:46 UTC, koalex commented on 1-module/1-task/index.js
> +    console.log(i);
Удалить `console.log`

2024-05-01 14:46 UTC, koalex commented on 1-module/2-task/index.js
> +  if (name !== null && name && name.length >= 4 && name.indexOf(" ") === -1) {
Можно сразу так:
`return name !== null && name && name.length >= 4 && name.indexOf(" ") === -1;`

2024-05-01 14:46 UTC, koalex commented on 1-module/4-task/index.js
> +  if (str.includes("1xbet") || str.includes("xxx")) {
Можно сразу так:
`return str.includes("1xbet") || str.includes("xxx");`

2024-05-01 14:51 UTC, jsru-1 commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-05-01 15:04 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @koalex

2024-05-01 15:07 UTC, koalex approved these changes

2024-05-01 15:07 UTC, koalex commented on 2-module/2-task/index.js
> +  if (arr.length === 0) {
Можно так:
`return arr.length === 0;`

2024-05-01 15:08 UTC, merged